sudo: required
dist: focal
before_install: ./.travis_native_dependencies.sh
before_script:
  - pip3 install --upgrade --ignore-installed --user parso
  - export PATH=$PWD/cgum:$PATH
  - export PATH=$PWD/pythonparser:$PATH
script: ./gradlew check
language: java
jdk:
  - openjdk11