sudo: required
dist: trusty
before_install: ./.travis_native_dependencies.sh
script: ./gradlew -Dgumtree.cgum.path=./cgum/cgum -Dgumtree.srcml.path=./srcML-src/bin/srcml check
after_success:
  - ./gradlew coveralls uploadArchives
language: java
jdk:
  - oraclejdk8
deploy:
  provider: bintray
  on:
    branch: develop
  file: deploy.json
  user: jrfaller
  key:
    secure: g2h46zuZoa9GJ/lGrAePdmI7P/KhH9zImSmdERl/qlYZ2aKD9a3GuBd94v5xsTtgOoftZK4KoRfp4Wvb5IEPQPPYEjQb1ubOT/xGxyySj3wcniTAWBa2U3FLDlhU3AyPO3xn1h8HUikm7zODDXGDZxDjDvI5hxRgBiz0j/P5j7A=
