sudo: required
dist: trusty
before_install:
  - wget http://131.123.42.38/lmcrs/beta/srcML-Ubuntu14.04.deb
  - sudo dpkg -i srcML-Ubuntu14.04.deb
language: java
jdk:
- oraclejdk8
deploy:
  provider: bintray
  on:
    branch: develop
  file: deploy.json
  user: jrfaller
  key:
    secure: g2h46zuZoa9GJ/lGrAePdmI7P/KhH9zImSmdERl/qlYZ2aKD9a3GuBd94v5xsTtgOoftZK4KoRfp4Wvb5IEPQPPYEjQb1ubOT/xGxyySj3wcniTAWBa2U3FLDlhU3AyPO3xn1h8HUikm7zODDXGDZxDjDvI5hxRgBiz0j/P5j7A=