name: Build, Test and Deploy Develop GumTree

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    container: gumtreediff/gumtree:latest
    if: ${{ github.event_name == 'pull_request' || !contains(github.event.head_commit.message, '[no ci]') }}
    steps:
      - name: checkout gumtree
        uses: actions/checkout@v2
      - name: build gumtree
        run: ./gradlew build
      - name: upload defects4j results
        uses: actions/upload-artifact@v2
        with:
          name: defects4j-report
          path: benchmark/build/reports/defects4j*
      - name: generate jacoco report
        run: ./gradlew jacocoRootReport
      - name: upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/reports/jacoco/jacocoRootReport/html/
      - name: upload snapshot package
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, '[snapshot]') }}
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}